/* global require, module */
/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * Config plugin for the `backup-exclusion` module (INV-PACK-11).
 *
 * iOS needs nothing here: exclusion is a per-file runtime flag, set by the native module.
 * Android has no runtime switch at all — exclusion can only be *declared*, so this plugin
 * writes the two rule files the platform reads and points `<application>` at them:
 *
 *   res/xml/backup_rules.xml          Auto Backup, API <= 30 (android:fullBackupContent)
 *   res/xml/data_extraction_rules.xml API 31+                (android:dataExtractionRules)
 *
 * Both are generated at prebuild and live under the generated `android/` tree, which is
 * never committed (INV-PLAT-02). Hand-editing them is therefore impossible to keep.
 */
const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withDangerousMod,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Named config. Paths are relative to the `root` backup domain, which is the app's data
 * directory — the parent of `files/`, `cache/`, `databases/`. `cache/packs` is
 * `Paths.cache` + `PACK_DB_DIRNAME` (`packages/schema/src/paths.ts`); packs are content-
 * addressed and re-downloadable, so backing them up would cost the user their iCloud or
 * Google quota for bytes we can always fetch again.
 *
 * Android never backs up `cache/` anyway. The rule is still declared: the default is a
 * platform convention, and this is a release gate.
 */
const EXCLUDED_ROOT_PATHS = ['cache/packs'];

const BACKUP_RULES_FILE = 'backup_rules.xml';
const DATA_EXTRACTION_RULES_FILE = 'data_extraction_rules.xml';
const GENERATED_BY = 'modules/backup-exclusion/app.plugin.js';

const excludes = (indent) =>
  EXCLUDED_ROOT_PATHS.map((p) => `${indent}<exclude domain="root" path="${p}" />`).join('\n');

const backupRulesXml = () => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ${GENERATED_BY}. Do not edit: android/ is regenerated by prebuild. -->
<full-backup-content>
${excludes('  ')}
</full-backup-content>
`;

const dataExtractionRulesXml = () => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ${GENERATED_BY}. Do not edit: android/ is regenerated by prebuild. -->
<data-extraction-rules>
  <cloud-backup>
${excludes('    ')}
  </cloud-backup>
  <device-transfer>
${excludes('    ')}
  </device-transfer>
</data-extraction-rules>
`;

const withBackupRuleFiles = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      await fs.promises.mkdir(xmlDir, { recursive: true });
      await fs.promises.writeFile(path.join(xmlDir, BACKUP_RULES_FILE), backupRulesXml(), 'utf8');
      await fs.promises.writeFile(
        path.join(xmlDir, DATA_EXTRACTION_RULES_FILE),
        dataExtractionRulesXml(),
        'utf8',
      );
      return cfg;
    },
  ]);

const withBackupManifestAttributes = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:fullBackupContent'] = '@xml/backup_rules';
    application.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';
    return cfg;
  });

const withBackupExclusion = (config) => withBackupManifestAttributes(withBackupRuleFiles(config));

module.exports = createRunOncePlugin(withBackupExclusion, 'backup-exclusion', '1.0.0');
